version: "3.4"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
    environment:
      - VITE_FASTAPI_SERVICE_URL=http://localhost:8000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
